server:
  port: 9000
spring:
  application:
    name: autherization service
  config:
      import: optional:configserver:http://localhost:8888
com:
  caloriedoc:
    user-service:
      name: user-service
      url: localhost:8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true