server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: food-service
          uri: http://localhost:8081/
          predicates:
            - Path=/apis/foodItems/**
        - id: user-service
          uri: http://localhost:8082/
          predicates:
            - Path=/apis/users/**
        - id: auth-service
          uri: http://localhost:9000/
          predicates:
            - Path=/apis/login/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true