export const COMPONENT_NAME = {
    MEAL_CARD: 'mealCard',
    MEAL_TITLE: 'mealTitle',
    MEAL_CALORIES: 'mealCalories',
    MEAL_ADD_BUTTON: 'mealAddButton',
};

export const ELEMENT_ID = {
    MEAL_CARD_BEARKFAST: `${COMPONENT_NAME.MEAL_CARD}Breakfast`,
    MEAL_CARD_BEARKFAST_TITLE: `${COMPONENT_NAME.MEAL_TITLE}Breakfast`,
    MEAL_CARD_BEARKFAST_CALORIES: `${COMPONENT_NAME.MEAL_CALORIES}Breakfast`,
    MEAL_CARD_BEARKFAST_ADD: `${COMPONENT_NAME.MEAL_ADD_BUTTON}Breakfast`,
    MEAL_CARD_MORNING_SNACK: `${COMPONENT_NAME.MEAL_CARD}MorningSnack`,
    MEAL_CARD_MORNING_SNACK_TITLE: `${COMPONENT_NAME.MEAL_TITLE}Breakfast`,
    MEAL_CARD_MORNING_SNACK_CALORIES: `${COMPONENT_NAME.MEAL_CALORIES}Breakfast`,
    MEAL_CARD_MORNING_SNACK_ADD: `${COMPONENT_NAME.MEAL_ADD_BUTTON}Breakfast`,
    MEAL_CARD_LUNCH: `${COMPONENT_NAME.MEAL_CARD}Lunch`,
    MEAL_CARD_EVENING_SNACK: `${COMPONENT_NAME.MEAL_CARD}EveningSnack`,
    MEAL_CARD_Dinner: `${COMPONENT_NAME.MEAL_CARD}Dinner`,
};
