server:
  port : 8082
spring:
  application:
    name: user-service
  data:
    mongodb:
      database: calorie-doc
      host: localhost
      port: 27017
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true